const products = [
  {
    user: "607f1f77bcf86cd799439011",
    name: "هدفون اپل ایرپادز پرو",
    images: [
      "/images/airpods.jpg",
      "/images/airpods-1.jpg",
      "/images/airpods-2.jpg",
    ],
    brand: "اپل",
    category: "الکترونیک",
    description: "هدفون با قابلیت حذف نویز فعال برای صدای غوطه‌ورکننده",
    reviews: [],
    likes: [],
    numLikes: 0,
    rating: 0,
    numReviews: 0,
    price: 12000000,
    countInStock: 15,
  },
  {
    user: "607f1f77bcf86cd799439014",
    name: "آیفون 13 پرو",
    images: [
      "/images/iphone13.avif",
      "/images/iphone13-1.jpg",
      "/images/iphone13-2.jpg",
    ],
    brand: "اپل",
    category: "الکترونیک",
    description: "سیستم سه دوربین تحول‌آفرین",
    reviews: [],
    likes: [],
    numLikes: 0,
    rating: 0,
    numReviews: 0,
    price: 50000000,
    countInStock: 8,
  },
  {
    user: "607f1f77bcf86cd799439016",
    name: "پلی‌استیشن 5 سونی",
    images: [
      "/images/playstation.jpg",
      "/images/playstation-1.jpg",
      "/images/playstation-2.jpg",
    ],
    brand: "سونی",
    category: "الکترونیک",
    description: "کنسول بازی نسل جدید با SSD فوق سریع",
    reviews: [],
    likes: [],
    numLikes: 0,
    rating: 0,
    numReviews: 0,
    price: 25000000,
    countInStock: 5,
  },
  {
    user: "607f1f77bcf86cd799439017",
    name: "ماوس لاجیتک MX Master 3",
    images: ["/images/logitechmouse.jpg", "/images/logitechmouse-1.jpg"],
    brand: "لاجیتک",
    category: "الکترونیک",
    description: "ماوس بی‌سیم پیشرفته برای کارهای حرفه‌ای",
    reviews: [],
    likes: [],
    numLikes: 0,
    rating: 0,
    numReviews: 0,
    price: 5000000,
    countInStock: 12,
  },
  {
    user: "607f1f77bcf86cd799439020",
    name: "آمازون اکو دات (نسل چهارم)",
    images: ["/images/echodot.jpg", "/images/echodot-1.jpg"],
    brand: "آمازون",
    category: "الکترونیک",
    description: "بلندگوی هوشمند با الکسا",
    reviews: [],
    likes: [],
    numLikes: 0,
    rating: 0,
    numReviews: 0,
    price: 2500000,
    countInStock: 20,
  },
  {
    user: "607f1f77bcf86cd799439022",
    name: "کفش نایکی Air Force 1 '07",
    images: [
      "/images/nikeairforce1.png",
      "/images/nikeairforce1-1.jpg",
      "/images/nikeairforce1-2.jpg",
    ],
    brand: "نایکی",
    category: "کفش",
    description: "کفش ورزشی کلاسیک سفید",
    reviews: [],
    likes: [],
    numLikes: 0,
    rating: 0,
    numReviews: 0,
    price: 5500000,
    countInStock: 10,
  },
  {
    user: "607f1f77bcf86cd799439023",
    name: "مانیتور گیمینگ سامسونگ 49 اینچ CHG90",
    images: ["/images/CHG90.jfif", "/images/CHG90-1.jpg"],
    brand: "سامسونگ",
    category: "الکترونیک",
    description: "مانیتور فوق عریض خمیده برای بازی",
    reviews: [],
    likes: [],
    numLikes: 0,
    rating: 0,
    numReviews: 0,
    price: 50000000,
    countInStock: 3,
  },
  {
    user: "607f1f77bcf86cd799439028",
    name: "فیت‌بیت Charge 5",
    images: ["/images/charge5.jpg", "/images/charge5-1.jpg"],
    brand: "فیت‌بیت",
    category: "الکترونیک",
    description: "ردیاب پیشرفته سلامت و تناسب اندام",
    reviews: [],
    likes: [],
    numLikes: 0,
    rating: 0,
    numReviews: 0,
    price: 9000000,
    countInStock: 9,
  },
  {
    user: "607f1f77bcf86cd799439031",
    name: "جاروبرقی بی‌سیم دایسون V11 Torque Drive",
    images: ["/images/V11Torque.jpg", "/images/V11Torque-1.jpg"],
    brand: "دایسون",
    category: "خانه",
    description: "جاروبرقی قدرتمند بی‌سیم با مکش هوشمند",
    reviews: [],
    likes: [],
    numLikes: 0,
    rating: 0,
    numReviews: 0,
    price: 30000000,
    countInStock: 4,
  },
  {
    user: "617a1b7d8f9d8b001f2e3a01",
    name: "گوشی شیائومی ردمی نوت 11",
    images: ["/images/note11.jpg", "/images/note11-1.jpg"],
    brand: "شیائومی",
    category: "موبایل",
    description: "گوشی هوشمند با پردازنده قدرتمند و باتری 5000 میلی‌آمپری",
    reviews: [],
    likes: [],
    numLikes: 0,
    rating: 0,
    numReviews: 0,
    price: 8500000,
    countInStock: 25,
  },
  {
    user: "617a1b7d8f9d8b001f2e3a03",
    name: "لبتاب ایسوس ویووبوک 15",
    images: ["/images/viewbook15.jpg", "/images/viewbook15-1.jpg"],
    brand: "ایسوس",
    category: "لپ‌تاپ",
    description: "لپ‌تاپ سبک و قدرتمند با پردازنده Core i5 نسل 11",
    reviews: [],
    likes: [],
    numLikes: 0,
    rating: 0,
    numReviews: 0,
    price: 25000000,
    countInStock: 8,
  },
  {
    user: "617a1b7d8f9d8b001f2e3a04",
    name: "قهوه‌ساز دلمونتی",
    images: ["/images/delmonti.jpg", "/images/delmonti-1.jpg"],
    brand: "دلمونتی",
    category: "لوازم خانگی",
    description: "قهوه‌ساز اتوماتیک با قابلیت تنظیم دمای آب",
    reviews: [],
    likes: [],
    numLikes: 0,
    rating: 0,
    numReviews: 0,
    price: 4500000,
    countInStock: 12,
  },
  {
    user: "617a1b7d8f9d8b001f2e3a07",
    name: "کوله پشتی اسپرت آدیداس",
    images: ["/images/adidasbackpack.jpg", "/images/adidasbackpack-1.jpg"],
    brand: "آدیداس",
    category: "لوازم ورزشی",
    description: "کوله پشتی با طراحی ارگونومیک و جیب های متعدد",
    reviews: [],
    likes: [],
    numLikes: 0,
    rating: 0,
    numReviews: 0,
    price: 1800000,
    countInStock: 30,
  },
  {
    user: "617a1b7d8f9d8b001f2e3a08",
    name: "ساعت هوشمند هواوی جی تی 3",
    images: ["/images/GT3.jpg", "/images/GT3-1.jpg"],
    brand: "هواوی",
    category: "گجت هوشمند",
    description: "ساعت هوشمند با مانیتور AMOLED و ردیابی سلامت",
    reviews: [],
    likes: [],
    numLikes: 0,
    rating: 0,
    numReviews: 0,
    price: 6500000,
    countInStock: 15,
  },
  {
    user: "617a1b7d8f9d8b001f2e3a10",
    name: "پنل خورشیدی 100 وات",
    images: ["/images/solar-panel.png", "/images/solar-panel-1.jpg"],
    brand: "سولارکینگ",
    category: "تجهیزات انرژی",
    description: "پنل خورشیدی با راندمان بالا و مقاوم در برابر آب",
    reviews: [],
    likes: [],
    numLikes: 0,
    rating: 0,
    numReviews: 0,
    price: 9500000,
    countInStock: 7,
  },
  {
    user: "617a1b7d8f9d8b001f2e3a13",
    name: "هدفون بی‌سیم سامسونگ",
    images: [
      "/images/samsung-headphones.webp",
      "/images/samsung-headphones-1.jpg",
    ],
    brand: "سامسونگ",
    category: "لوازم صوتی",
    description: "هدفون با حذف نویز فعال و کیفیت صدای عالی",
    reviews: [],
    likes: [],
    numLikes: 0,
    rating: 0,
    numReviews: 0,
    price: 7500000,
    countInStock: 18,
  },
  // {
  //   user: "617a1b7d8f9d8b001f2e3a14",
  //   name: "ماشین لباسشویی ال جی 8 کیلویی",
  //   images: ["/images/washingmachine.jfif", "/images/washingmachine-1.jpg"],
  //   brand: "ال جی",
  //   category: "لوازم خانگی",
  //   description: "لباسشویی با موتور اینورتر و مصرف انرژی A++",
  //   reviews: []
  //     {
  //       user: "617a1b7d8f9d8b001f2e3a15",
  //       name: "فاطمه امینی",
  //       rating: 0,
  //       comment: "خیلی بی‌صدا کار میکنه و لباسها رو تمیز میشوره",
  //     },
  //   ],
  //   rating: 0,
  //   numReviews: 1,
  //   price: 22000000,
  //   countInStock: 5,
  // },
  {
    user: "617a1b7d8f9d8b001f2e3a16",
    name: "دوچرخه کوهستان تریک ایکس",
    images: ["/images/bicycle.jpg", "/images/bicycle-1.jpg"],
    brand: "تریک",
    category: "ورزشی",
    description: "دوچرخه با فریم آلومینیومی و دنده‌های شیفتون",
    reviews: [],
    likes: [],
    numLikes: 0,
    rating: 0,
    numReviews: 2,
    price: 15000000,
    countInStock: 4,
  },
  {
    user: "617a1b7d8f9d8b001f2e3a19",
    name: "دوربین کانن EOS 200D",
    images: ["/images/canoncamera.jfif", "/images/canoncamera-1.jpg"],
    brand: "کانن",
    category: "عکاسی",
    description: "دوربین DSLR با سنسور 24 مگاپیکسلی و صفحه نمایش چرخشی",
    reviews: [],
    likes: [],
    numLikes: 0,
    rating: 0,
    numReviews: 0,
    price: 28000000,
    countInStock: 6,
  },
];

export default products;
